name: Duster Fix

# Commits made in here will not trigger any workflows
# Checkout Duster's documentation for a workaround

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main, development ]

jobs:
  duster:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: php-actions/composer@master
        with:
          php_version: '8.2'

      - name: "Duster Fix"
        run: vendor/bin/duster fix --using "phpstan,tlint,pint"

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto_commit_action
        with:
          commit_message: Dusting
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com

      - name: Ignore Duster commit in git blame
        if: steps.auto_commit_action.outputs.changes_detected == 'true'
        run: echo ${{ steps.auto_commit_action.outputs.commit_hash }} >> .git-blame-ignore-revs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Ignore Dusting commit in git blame
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com

  tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
    
        - name: Validate composer.json and composer.lock
          run: composer validate --strict
    
        - name: Cache Composer packages
          id: composer-cache
          uses: actions/cache@v3
          with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-
    
        - name: Install dependencies
          run: composer install --prefer-dist --no-progress
        

        - name: Run Tests
          run: php artisan test --coverage --min=80
